#! /bin/sh

# Add room for panel on primary monitor
xrandr --output DP-4 --primary --left-of DP-2

compton --vsync=opengl &
sxhkd &
lxqt-panel &

bspc monitor DP-4 -d 1 2 3
bspc monitor DP-2 -d 1 2 3

bspc config -m DP-4 bottom_padding 34
bspc config border_width 3
bspc config focused_border_color '#ffbe63'
bspc config presel_feedback_color '#999999'
bspc config pointer_modifier mod4
bspc config click_to_focus true

bspc config split_ratio 0.6

bspc config history_aware_focus true
bspc config auto_cancel true

# Special rules
bspc rule -a lxqt-panel manage=off
